### ISSUE TITLE
opencv in pure golang

### ISSUE THREAD

**Issue by gedw99** [pidgy/unitehud#4]
https://github.com/esimov/pigo might make it faster according to https://github.com/esimov/pigo#benchmark-results

Curious what you think since from looking at your code your doing the OCR calcs yourself in https://github.com/pidgy/unitehud/tree/master/match looking for specific things ?

pigo as i understand it is trained

**Comment by pidgy** [comment]
Hey @gedw99 sorry for the late response! I am will try this out and let you know how it goes. 

Thanks for submitting this, great find.

**Comment by pidgy** [comment]
going to move this to closed, lovely suggestion but afaik pigo is used for facial detection and wont apply here
